export {Game} from "./game/game";
export {Navbar} from "../components/navbar/navbar";
export {Setup} from "./setup/setup";
export {Home} from "./home/home";
export {Dashboard} from "./dashboard/dashboard";
export {Login} from "./login/login";
export {Register} from "./register/register";
export {ShogiDiagram} from "./shogiDiagram/shogiDiagram";
export {ChessDiagram} from "./chessDiagram/chessDiagram";